//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApplication.ServiceLayer.DataContracts
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PersonData", Namespace = "http://tempuri.org/MyWebApplication.xsd")]
    public partial class PersonData : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int PersonKeyField;

        private string PersonTypeField;

        private bool PersonStyleField;

        private string TitleField;

        private string FirstNameField;

        private string MiddleNameField;

        private string LastNameField;

        private string SuffixField;

        private int EmailPromotionField;

        private string AdditionalContactInfoField;

        private string DemographicsField;

        private string RowGuidField;

        private System.Nullable<System.DateTime> ModifiedDateField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonKey
        {
            get
            {
                return this.PersonKeyField;
            }
            set
            {
                this.PersonKeyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string PersonType
        {
            get
            {
                return this.PersonTypeField;
            }
            set
            {
                this.PersonTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public bool PersonStyle
        {
            get
            {
                return this.PersonStyleField;
            }
            set
            {
                this.PersonStyleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string Suffix
        {
            get
            {
                return this.SuffixField;
            }
            set
            {
                this.SuffixField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public int EmailPromotion
        {
            get
            {
                return this.EmailPromotionField;
            }
            set
            {
                this.EmailPromotionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 9)]
        public string AdditionalContactInfo
        {
            get
            {
                return this.AdditionalContactInfoField;
            }
            set
            {
                this.AdditionalContactInfoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public string Demographics
        {
            get
            {
                return this.DemographicsField;
            }
            set
            {
                this.DemographicsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 11)]
        public string RowGuid
        {
            get
            {
                return this.RowGuidField;
            }
            set
            {
                this.RowGuidField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 12)]
        public System.Nullable<System.DateTime> ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
    }
}
