//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApplication.Common.MyWebApplicationProxy
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PersonData", Namespace = "http://tempuri.org/MyWebApplication.xsd")]
    public partial class PersonData : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int PersonKeyField;

        private string PersonTypeField;

        private bool PersonStyleField;

        private string TitleField;

        private string FirstNameField;

        private string MiddleNameField;

        private string LastNameField;

        private string SuffixField;

        private int EmailPromotionField;

        private string AdditionalContactInfoField;

        private string DemographicsField;

        private string RowGuidField;

        private System.Nullable<System.DateTime> ModifiedDateField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonKey
        {
            get
            {
                return this.PersonKeyField;
            }
            set
            {
                this.PersonKeyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string PersonType
        {
            get
            {
                return this.PersonTypeField;
            }
            set
            {
                this.PersonTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public bool PersonStyle
        {
            get
            {
                return this.PersonStyleField;
            }
            set
            {
                this.PersonStyleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string Suffix
        {
            get
            {
                return this.SuffixField;
            }
            set
            {
                this.SuffixField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public int EmailPromotion
        {
            get
            {
                return this.EmailPromotionField;
            }
            set
            {
                this.EmailPromotionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 9)]
        public string AdditionalContactInfo
        {
            get
            {
                return this.AdditionalContactInfoField;
            }
            set
            {
                this.AdditionalContactInfoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public string Demographics
        {
            get
            {
                return this.DemographicsField;
            }
            set
            {
                this.DemographicsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 11)]
        public string RowGuid
        {
            get
            {
                return this.RowGuidField;
            }
            set
            {
                this.RowGuidField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 12)]
        public System.Nullable<System.DateTime> ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.ode.state.oh.us/IDashboardQuery/", ConfigurationName = "MyWebApplication.Common.MyWebApplicationProxy.IMyWebApplicationService")]
    public interface IMyWebApplicationService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ode.state.oh.us/IDashboardQuery/IMyWebApplicationService/ListPersons", ReplyAction = "http://www.ode.state.oh.us/IDashboardQuery/IMyWebApplicationService/ListPersonsRe" +
            "sponse")]
        MyWebApplication.Common.MyWebApplicationProxy.ListPersonsResponse ListPersons(MyWebApplication.Common.MyWebApplicationProxy.ListPersonsRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ListPersonsRequest", WrapperNamespace = "http://www.dashboard.state.oh.us/dashboard.ws", IsWrapped = true)]
    public partial class ListPersonsRequest
    {

        public ListPersonsRequest()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetPersonsResponse", WrapperNamespace = "http://www.dashboard.state.oh.us/dashboard.ws", IsWrapped = true)]
    public partial class ListPersonsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.dashboard.state.oh.us/dashboard.ws", Order = 0)]
        public MyWebApplication.Common.MyWebApplicationProxy.PersonData[] PersonList;

        public ListPersonsResponse()
        {
        }

        public ListPersonsResponse(MyWebApplication.Common.MyWebApplicationProxy.PersonData[] PersonList)
        {
            this.PersonList = PersonList;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IMyWebApplicationServiceChannel : MyWebApplication.Common.MyWebApplicationProxy.IMyWebApplicationService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MyWebApplicationServiceClient : System.ServiceModel.ClientBase<MyWebApplication.Common.MyWebApplicationProxy.IMyWebApplicationService>, MyWebApplication.Common.MyWebApplicationProxy.IMyWebApplicationService
    {

        public MyWebApplicationServiceClient()
        {
        }

        public MyWebApplicationServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public MyWebApplicationServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public MyWebApplicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public MyWebApplicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public MyWebApplication.Common.MyWebApplicationProxy.ListPersonsResponse ListPersons(MyWebApplication.Common.MyWebApplicationProxy.ListPersonsRequest request)
        {
            return base.Channel.ListPersons(request);
        }
    }
}
